version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - TRAKT_CLIENT_ID=your_trakt_client_id
      - TRAKT_CLIENT_SECRET=your_trakt_client_secret
      - REDIRECT_URI=http://localhost:3000/auth/callback
    depends_on:
      - redis
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  redis:
    image: redis
    ports:
      - "6379:6379"
